######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 10 11:08:17 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gpmainwindow.h
FORMS += gpmainwindow.ui
SOURCES += gpmainwindow.cpp main.cpp
