CC=gcc
CFLAGS=-c -I../libs/libplist/include/ -I../libs/libimobiledevice/include/ -I../includes/ -I/usr/local/include/ -Iinclude/ -I/opt/local/include/ -m32 -w -ggdb

all:
	@$(CC) $(CFLAGS) *.cpp

clean:
	@rm *.o

